org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.249
neo_version_range=[21.1.233,21.2)
loader_version_range=[1,)

# Create
create_version=6.0.10-280
create_version_range=[6.0.10,)

# Create S&A
create_sa_file_id=8664066
create_sa_version_range=[2.1.3,)

# Other Dependencies
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
jei_version=19.27.0.336

## Mod Properties
mod_id=create_netherite_stuff_additions
mod_name=Create Netherite Stuff 'N Additions
mod_license=Academic Free License v3.0
mod_version=1.0.0
mod_group_id=ru.lotuze.createnetheritestuffadditions
mod_authors=lotuze
