modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]

modId="${mod_id}"

version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"

description='''
An addon for Create: Stuff 'N Additions that adds a Netherite Drill.

The Netherite Drill is a stronger upgrade to the portable drill from Create: Stuff 'N Additions.
It is designed to be comparable to Netherite-tier tools and can mine tougher blocks that the original drill cannot handle.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_sa"
    type="required"
    versionRange="${create_sa_version_range}"
    ordering="AFTER"
    side="BOTH"